### ISSUE TITLE
Update README.md

### ISSUE THREAD

**Issue by Sengeki1** [victorberdugo1/SDL-Tutorial-for-your-Android-Projects#1]
In the Instalation section update the link for the fork because its not using your github name but instead a demo name.

it should be 
```bash
git clone  https://github.com/victorberdugo1/SDL-Tutorial-for-your-Android-Projects.git
cd SDL-Android-Tutorial
```

**Comment by victorberdugo1** [comment]
Thanks for pointing that out! I've updated the link in the installation section to point to my GitHub repo.
Appreciate the heads-up!
